apiVersion: apps/v1
kind: Deployment
metadata:
  name: popular-movies-integration
  namespace: popular-movies-integration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: popular-movies-integration
  template:
    metadata:
      labels:
        app: popular-movies-integration
    spec:
      containers:
        - name: app
          image: aleferod/popular-movies-integration:development
          ports:
            - name: http
              protocol: TCP
              containerPort: 80
            - name: localstack
              protocol: TCP
              containerPort: 4566
            - name: splunk
              protocol: TCP
              containerPort: 8088
          env:
            - name: APP_PORT
              value: "8081"
            - name: AWS_DEFAULT_REGION
              value: us-east-1
            - name: AWS_ACCESS_KEY_ID
              value: admin
            - name: AWS_SECRET_ACCESS_KEY
              value: admin
            - name: THE_MOVIE_DB_URL
              value: https://api.themoviedb.org/3
            - name: THE_MOVIE_DB_API_KEY
              value: edac97aabe9e5bc96b11219190aab292
            - name: RATE_MOVIE_SQS_QUEUE_NAME
              value: rate-movie
            - name: AWS_LOCALSTACK_URL
              value: http://192.168.49.2:31240
            - name: AWS_LOCALSTACK_REGION
              value: us-east-1
            - name: SPLUNK_URL
              value: http://192.168.49.2:32635
            - name: SPLUNK_TOKEN
              value: 7b611280-7af3-41f9-8bac-bcc7f854f68e
            - name: SPLUNK_INDEX
              value: popular-movies-integration
            - name: SPLUNK_SOURCE
              value: http-event-logs
            - name: SPLUNK_SOURCE_TYPE
              value: log4j
          imagePullPolicy: Always