apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: k8s-popular-movies-integration-autoscaler
  namespace: popular-movies-integration
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: popular-movies-integration-app
  targetCPUUtilizationPercentage: 50

