apiVersion: v1
kind: Service
metadata:
  name: popular-movies-integration
spec:
  selector:
    app: popular-movies-integration
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: http-https-ssl
      port: 443
      targetPort: http
  type: LoadBalancer