apiVersion: v1
kind: Service
metadata:
  name: splunk-entrypoint
  namespace: monitoring
spec:
  type: LoadBalancer
  selector:
    splunk: web
  ports:
  - name: "8000"
    port: 8000
    targetPort: 8000
  - name: "9997"
    port: 9997
    targetPort: 9997
  - name: "8088"
    port: 8088
    targetPort: 8088
  - name: "1514"
    port: 1514
    targetPort: 1514s