apiVersion: apps/v1
kind: Deployment
metadata:
  name: popular-movies-integration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: popular-movies-integration
  template:
    metadata:
      labels:
        app: popular-movies-integration
    spec:
      containers:
        - name: app
          image: aleferod/popular-movies-integration:development
          ports:
            - name: http
              protocol: TCP
              containerPort: 80
            - name: localstack
              protocol: TCP
              containerPort: 4566
          env:
            - name: AWS_DEFAULT_REGION
              value: us-east-1
            - name: AWS_ACCESS_KEY_ID
              value: admin
            - name: AWS_SECRET_ACCESS_KEY
              value: admin
          imagePullPolicy: Always