name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: 'adopt'
    - name: Build with Gradle
      working-directory: ./app
      run: ./gradlew build
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_HUB_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_HUB_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
    - name: Build the Docker image
      working-directory: ./app
      run: docker build . --file Dockerfile --tag aleferod/popular-movies-integration:development
      
    - name: Docker Push
      run: docker push aleferod/popular-movies-integration:development
